In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pandas.plotting import scatter_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.optim as optim

# Data

In [2]:
# data_path = "/kaggle/input/traffic/data.csv"
data_path = "data.csv"

df = pd.read_csv(data_path)


In [3]:
df = df[df['Dst Port'] != 'Dst Port']

df['Dst Port'] = df['Dst Port'].astype(int)
df['Protocol'] = df['Protocol'].astype(int)
df['Flow Duration'] = df['Flow Duration'].astype(int)
df['Tot Fwd Pkts'] = df['Tot Fwd Pkts'].astype(int)
df['Tot Bwd Pkts'] = df['Tot Bwd Pkts'].astype(int)
df['TotLen Fwd Pkts'] = df['TotLen Fwd Pkts'].astype(int)
df['TotLen Bwd Pkts'] = df['TotLen Bwd Pkts'].astype(int)
df['Fwd Pkt Len Max'] = df['Fwd Pkt Len Max'].astype(int)
df['Fwd Pkt Len Min'] = df['Fwd Pkt Len Min'].astype(int)
df['Fwd Pkt Len Mean'] = df['Fwd Pkt Len Mean'].astype(float)
df['Fwd Pkt Len Std'] = df['Fwd Pkt Len Std'].astype(float)
df['Bwd Pkt Len Max'] = df['Bwd Pkt Len Max'].astype(int)
df['Bwd Pkt Len Min'] = df['Bwd Pkt Len Min'].astype(int)
df['Bwd Pkt Len Mean'] = df['Bwd Pkt Len Mean'].astype(float)
df['Bwd Pkt Len Std'] = df['Bwd Pkt Len Std'].astype(float)
df['Flow Byts/s'] = df['Flow Byts/s'].astype(float)
df['Flow Pkts/s'] = df['Flow Pkts/s'].astype(float)
df['Flow IAT Mean'] = df['Flow IAT Mean'].astype(float)
df['Flow IAT Std'] = df['Flow IAT Std'].astype(float)
df['Flow IAT Max'] = df['Flow IAT Max'].astype(int)
df['Flow IAT Min'] = df['Flow IAT Min'].astype(int)
df['Fwd IAT Tot'] = df['Fwd IAT Tot'].astype(int)
df['Fwd IAT Mean'] = df['Fwd IAT Mean'].astype(float)
df['Fwd IAT Std'] = df['Fwd IAT Std'].astype(float)
df['Fwd IAT Max'] = df['Fwd IAT Max'].astype(int)
df['Fwd IAT Min'] = df['Fwd IAT Min'].astype(int)
df['Bwd IAT Tot'] = df['Bwd IAT Tot'].astype(int)
df['Bwd IAT Mean'] = df['Bwd IAT Mean'].astype(float)
df['Bwd IAT Std'] = df['Bwd IAT Std'].astype(float)
df['Bwd IAT Max'] = df['Bwd IAT Max'].astype(int)
df['Bwd IAT Min'] = df['Bwd IAT Min'].astype(int)
df['Fwd PSH Flags'] = df['Fwd PSH Flags'].astype(int)
df['Bwd PSH Flags'] = df['Bwd PSH Flags'].astype(int)
df['Fwd URG Flags'] = df['Fwd URG Flags'].astype(int)
df['Bwd URG Flags'] = df['Bwd URG Flags'].astype(int)
df['Fwd Header Len'] = df['Fwd Header Len'].astype(int)
df['Bwd Header Len'] = df['Bwd Header Len'].astype(int)
df['Fwd Pkts/s'] = df['Fwd Pkts/s'].astype(float)
df['Bwd Pkts/s'] = df['Bwd Pkts/s'].astype(float)
df['Pkt Len Min'] = df['Pkt Len Min'].astype(int)
df['Pkt Len Max'] = df['Pkt Len Max'].astype(int)
df['Pkt Len Mean'] = df['Pkt Len Mean'].astype(float)
df['Pkt Len Std'] = df['Pkt Len Std'].astype(float)
df['Pkt Len Var'] = df['Pkt Len Var'].astype(float)
df['FIN Flag Cnt'] = df['FIN Flag Cnt'].astype(int)
df['SYN Flag Cnt'] = df['SYN Flag Cnt'].astype(int)
df['RST Flag Cnt'] = df['RST Flag Cnt'].astype(int)
df['PSH Flag Cnt'] = df['PSH Flag Cnt'].astype(int)
df['ACK Flag Cnt'] = df['ACK Flag Cnt'].astype(int)
df['URG Flag Cnt'] = df['URG Flag Cnt'].astype(int)
df['CWE Flag Count'] = df['CWE Flag Count'].astype(int)
df['ECE Flag Cnt'] = df['ECE Flag Cnt'].astype(int)
df['Down/Up Ratio'] = df['Down/Up Ratio'].astype(int)
df['Pkt Size Avg'] = df['Pkt Size Avg'].astype(float)
df['Fwd Seg Size Avg'] = df['Fwd Seg Size Avg'].astype(float)
df['Bwd Seg Size Avg'] = df['Bwd Seg Size Avg'].astype(float)
df['Fwd Byts/b Avg'] = df['Fwd Byts/b Avg'].astype(int)
df['Fwd Pkts/b Avg'] = df['Fwd Pkts/b Avg'].astype(int)
df['Fwd Blk Rate Avg'] = df['Fwd Blk Rate Avg'].astype(int)
df['Bwd Byts/b Avg'] = df['Bwd Byts/b Avg'].astype(int)
df['Bwd Pkts/b Avg'] = df['Bwd Pkts/b Avg'].astype(int)
df['Bwd Blk Rate Avg'] = df['Bwd Blk Rate Avg'].astype(int)
df['Subflow Fwd Pkts'] = df['Subflow Fwd Pkts'].astype(int)
df['Subflow Fwd Byts'] = df['Subflow Fwd Byts'].astype(int)
df['Subflow Bwd Pkts'] = df['Subflow Bwd Pkts'].astype(int)
df['Subflow Bwd Byts'] = df['Subflow Bwd Byts'].astype(int)
df['Init Fwd Win Byts'] = df['Init Fwd Win Byts'].astype(int)
df['Init Bwd Win Byts'] = df['Init Bwd Win Byts'].astype(int)
df['Fwd Act Data Pkts'] = df['Fwd Act Data Pkts'].astype(int)
df['Fwd Seg Size Min'] = df['Fwd Seg Size Min'].astype(int)
df['Active Mean'] = df['Active Mean'].astype(float)
df['Active Std'] = df['Active Std'].astype(float)
df['Active Max'] = df['Active Max'].astype(int)
df['Active Min'] = df['Active Min'].astype(int)
df['Idle Mean'] = df['Idle Mean'].astype(float)
df['Idle Std'] = df['Idle Std'].astype(float)
df['Idle Max'] = df['Idle Max'].astype(int)
df['Idle Min'] = df['Idle Min'].astype(int)

In [4]:
df.drop(["Timestamp"], axis=1, inplace=True)
df.drop(["Dst Port"], axis=1, inplace=True)

df["Flow Byts/s"] = df["Flow Byts/s"].replace(np.inf, np.nan)
df["Flow Pkts/s"] = df["Flow Pkts/s"].replace(np.inf, np.nan)

df["Flow Pkts/s"] = df["Flow Pkts/s"].replace(np.nan, df["Flow Pkts/s"].max())

In [5]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

df.dropna(inplace=True)


## Label encode

In [6]:
df['Label'].values
# how many rows with Label == 'DoS attacks-SynFlood'
print(df[df['Label'] == 'DoS attacks-SynFlood'].shape[0])

270


In [7]:
vec_len = len(df['Label'].unique())

In [8]:
ohe = OneHotEncoder(sparse_output=False)
labels_onehot = ohe.fit_transform(df['Label'].values.reshape(-1, 1))

onehot_df = pd.DataFrame(labels_onehot, columns=ohe.categories_[0], index=df.index)

df = pd.concat([df.drop(columns=['Label']), onehot_df], axis=1)

In [9]:
df.head()

Protocol  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  \
0         6            165             2             0                0   
1         6        5727100             4             4               97   
2         6        4053796            14             8             1456   
3         6         833502             7             5              364   
4        17            601             1             1               53   

   TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  \
0                0                0                0              0.00   
1              231               97                0             24.25   
2             1731              741                0            104.00   
3              582              103                0             52.00   
4               85               53               53             53.00   

   Fwd Pkt Len Std  ...  DDOS attack-LOIC-UDP  DoS attacks-GoldenEye  \
0         0.000000  ...                   0.0                    0.0   
1        48.500000  ...                   0.0                    0.0   
2       195.013609  ...                   0.0                    0.0   
3        49.217206  ...                   0.0                    0.0   
4         0.000000  ...                   0.0                    0.0   

   DoS attacks-Hulk  DoS attacks-SlowHTTPTest  DoS attacks-Slowloris  \
0               0.0                       0.0                    0.0   
1               0.0                       0.0                    0.0   
2               0.0                       0.0                    0.0   
3               0.0                       0.0                    0.0   
4               0.0                       0.0                    0.0   

   DoS attacks-SynFlood  FTP-BruteForce  Infilteration  SQL Injection  \
0                   0.0             0.0            0.0            0.0   
1                   0.0             0.0            0.0            0.0   
2                   0.0             0.0            0.0            0.0   
3                   0.0             0.0            0.0            0.0   
4                   0.0             0.0            0.0            0.0   

   SSH-Bruteforce  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  

[5 rows x 92 columns]

In [10]:
print(labels_onehot)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Drop low corr with Label

In [11]:
corr_matrix = df.corr(numeric_only=True)
corr_pairs = corr_matrix.unstack()
threshold = 0.9
strong_corr = corr_pairs[
    (abs(corr_pairs) > threshold)
    & (corr_pairs != 1)
    & (corr_pairs.index.get_level_values(0) != corr_pairs.index.get_level_values(1))
]
strong_corr = strong_corr.sort_values(ascending=False)
pd.set_option("display.max_rows", None)

print(strong_corr)

Fwd Act Data Pkts     Tot Fwd Pkts            1.000000
Tot Fwd Pkts          Fwd Act Data Pkts       1.000000
Fwd Act Data Pkts     Subflow Fwd Pkts        1.000000
Subflow Fwd Pkts      Fwd Act Data Pkts       1.000000
Tot Fwd Pkts          Fwd Header Len          0.999998
Fwd Header Len        Tot Fwd Pkts            0.999998
Subflow Fwd Pkts      Fwd Header Len          0.999998
Fwd Header Len        Subflow Fwd Pkts        0.999998
Fwd Act Data Pkts     Fwd Header Len          0.999996
Fwd Header Len        Fwd Act Data Pkts       0.999996
                      Subflow Fwd Byts        0.999948
                      TotLen Fwd Pkts         0.999948
TotLen Fwd Pkts       Fwd Header Len          0.999948
Subflow Fwd Byts      Fwd Header Len          0.999948
TotLen Fwd Pkts       Tot Fwd Pkts            0.999929
Subflow Fwd Byts      Tot Fwd Pkts            0.999929
                      Subflow Fwd Pkts        0.999929
Tot Fwd Pkts          TotLen Fwd Pkts         0.999929
Subflow Fw

In [12]:
cols_to_drop = set()

for col1, col2 in strong_corr.index:
    if col1 not in cols_to_drop:
        cols_to_drop.add(col2)

cols_to_drop.remove('DDOS attack-LOIC-UDP')


In [13]:
df_final = df.drop(columns=cols_to_drop, axis=1)

In [14]:
df_final.to_csv("model/train_data.csv", index=False)
df_final.shape

(10526, 67)

## Train test split

In [15]:
X = df_final.iloc[:, :-15]
y = df_final.iloc[:, -15:]

print(X.columns)
print(y.columns)
print(X.shape)
print(y.shape)

Index(['Protocol', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'Fwd Pkt Len Min',
       'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Min',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow IAT Mean', 'Flow IAT Std',
       'Fwd IAT Tot', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min',
       'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags',
       'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Std', 'Pkt Len Var',
       'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt',
       'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt',
       'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Bwd Pkts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Seg Size Min',
       'Active Std', 'Active Max', 'Active Min', 'Idle Std'],
      dtype='object')
Index(['Ben

In [16]:
# perform stratified sampling
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

y_train = y_train.to_numpy()  # Convert to numpy
y_test = y_test.to_numpy()    # Convert to numpy

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([8420, 52])
torch.Size([8420, 15])


# Model

In [17]:
class DNN(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(DNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 16)
        self.output = nn.Linear(16, num_classes)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = torch.softmax(self.output(x), dim=1)
        return x

In [18]:
input_dim = X.shape[1]
output_dim = y.shape[1]
model = DNN(input_dim, output_dim)
print(model)

DNN(
  (fc1): Linear(in_features=52, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=16, bias=True)
  (output): Linear(in_features=16, out_features=15, bias=True)
)


In [19]:
loss_fn = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


In [20]:
epochs = 50
batch_size = 32

train_data = torch.utils.data.TensorDataset(X_train_tensor, y_train_tensor)
train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True)



for epoch in range(epochs):
    model.train()
    epoch_loss = 0
    
    for batch_X, batch_y in train_loader:
        # print("batch_y", batch_y)
        optimizer.zero_grad()
        predictions = model(batch_X)
        # print("predictions", predictions.shape)
        loss = loss_fn(predictions, batch_y)
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item()
    
        # print(predictions)
        # print(batch_y)
    print(f"Epoch {epoch+1}/{epochs}, Loss: {epoch_loss:.4f}")


Epoch 1/50, Loss: 185.7463
Epoch 2/50, Loss: 182.1045
Epoch 3/50, Loss: 181.0117
Epoch 4/50, Loss: 180.8121
Epoch 5/50, Loss: 180.5228
Epoch 6/50, Loss: 180.1609
Epoch 7/50, Loss: 180.1321
Epoch 8/50, Loss: 180.1210
Epoch 9/50, Loss: 180.0978
Epoch 10/50, Loss: 179.9838
Epoch 11/50, Loss: 179.9098
Epoch 12/50, Loss: 179.9201
Epoch 13/50, Loss: 179.9027
Epoch 14/50, Loss: 179.9379
Epoch 15/50, Loss: 179.9367
Epoch 16/50, Loss: 179.9114
Epoch 17/50, Loss: 179.9246
Epoch 18/50, Loss: 179.8934
Epoch 19/50, Loss: 179.8802
Epoch 20/50, Loss: 179.7183
Epoch 21/50, Loss: 179.4227
Epoch 22/50, Loss: 179.2665
Epoch 23/50, Loss: 179.3025
Epoch 24/50, Loss: 179.2732
Epoch 25/50, Loss: 179.2573
Epoch 26/50, Loss: 179.2857
Epoch 27/50, Loss: 179.2367
Epoch 28/50, Loss: 179.2447
Epoch 29/50, Loss: 179.2950
Epoch 30/50, Loss: 179.3099
Epoch 31/50, Loss: 179.2674
Epoch 32/50, Loss: 179.2393
Epoch 33/50, Loss: 179.2543
Epoch 34/50, Loss: 179.2339
Epoch 35/50, Loss: 179.2293
Epoch 36/50, Loss: 179.2970
E

In [21]:
model.eval()
with torch.no_grad():
    test_predictions = model(X_test_tensor)
    print(test_predictions)
    test_predictions = (test_predictions >= 0.5).float()

    correct_per_sample = test_predictions.eq(y_test_tensor).sum(dim=1) 
    total_labels_per_sample = y_test_tensor.size(1)
    accuracy_per_sample = correct_per_sample / total_labels_per_sample
    accuracy = accuracy_per_sample.mean().item()
    
    print(f"Test Accuracy: {accuracy:.4f}")
    
# print(probabilities)
class_idx = torch.argmax(test_predictions, dim=1)
print(class_idx)

unique_classes, counts = torch.unique(class_idx, return_counts=True)
value_counts = {int(cls): int(count) for cls, count in zip(unique_classes, counts)}
print(value_counts)



tensor([[5.9222e-05, 9.5372e-10, 3.1364e-06,  ..., 1.7159e-10, 1.6697e-11,
         5.9233e-06],
        [8.1892e-10, 8.4952e-12, 3.5194e-13,  ..., 4.7144e-12, 2.2055e-12,
         8.5963e-07],
        [1.0000e+00, 1.6690e-31, 1.3440e-37,  ..., 1.9411e-28, 4.5656e-34,
         2.2108e-20],
        ...,
        [1.0000e+00, 6.6337e-42, 0.0000e+00,  ..., 5.2076e-38, 0.0000e+00,
         5.8425e-18],
        [1.0000e+00, 1.0446e-40, 0.0000e+00,  ..., 1.6354e-36, 7.9874e-44,
         1.5123e-25],
        [1.0000e+00, 1.7399e-26, 4.6923e-31,  ..., 8.2437e-24, 4.2021e-28,
         4.7836e-17]])
Test Accuracy: 0.9777
tensor([4, 7, 0,  ..., 0, 0, 0])
{0: 1267, 2: 27, 4: 80, 5: 59, 6: 185, 7: 75, 8: 101, 9: 155, 10: 54, 11: 33, 14: 70}


In [22]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Giả định `test_predictions` và `y_test_tensor` đã được định nghĩa
test_predictions = (test_predictions >= 0.5).float()

# Precision, Recall và F1 tính cho từng lớp
precision = precision_score(y_test_tensor.numpy(), test_predictions.numpy(), average=None)
recall = recall_score(y_test_tensor.numpy(), test_predictions.numpy(), average=None)
f1 = f1_score(y_test_tensor.numpy(), test_predictions.numpy(), average=None)

# F2 score
beta = 2
f2 = [
    (1 + beta ** 2) * (p * r) / ((beta ** 2 * p) + r)
    for p, r in zip(precision, recall)
]

# In kết quả
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("F2 Score:", f2)


Precision: [0.76479874 0.         0.92592593 0.         1.         1.
 0.97297297 0.98666667 0.59405941 0.98709677 1.         0.90909091
 0.         0.         1.        ]
Recall: [0.99181167 0.         0.20491803 0.         1.         0.98333333
 1.         0.925      1.         0.99350649 1.         0.42857143
 0.         0.         1.        ]
F1 Score: [0.86363636 0.         0.33557047 0.         1.         0.99159664
 0.98630137 0.95483871 0.74534161 0.99029126 1.         0.58252427
 0.         0.         1.        ]
F2 Score: [0.936231884057971, nan, 0.24271844660194175, nan, 1.0, 0.9866220735785952, 0.994475138121547, 0.9367088607594937, 0.8797653958944281, 0.9922178988326847, 1.0, 0.47923322683706066, nan, nan, 1.0]


c:\Users\duong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\duong\AppData\Local\Temp\ipykernel_9212\3731498122.py:14: RuntimeWarning: invalid value encountered in scalar divide
  (1 + beta ** 2) * (p * r) / ((beta ** 2 * p) + r)


In [23]:
class_labels = ['Benign', 'Bot', 'Brute Force -Web', 'Brute Force -XSS',
       'DDOS attack-HOIC', 'DDOS attack-LOIC-UDP', 'DoS attacks-GoldenEye',
       'DoS attacks-Hulk', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Slowloris','DoS attacks-SynFlood',
       'FTP-BruteForce', 'Infilteration', 'SQL Injection', 'SSH-Bruteforce']

# Create mapper
mapper = {index + 1: label.lower() for index, label in enumerate(class_labels)}
print(mapper)


{1: 'benign', 2: 'bot', 3: 'brute force -web', 4: 'brute force -xss', 5: 'ddos attack-hoic', 6: 'ddos attack-loic-udp', 7: 'dos attacks-goldeneye', 8: 'dos attacks-hulk', 9: 'dos attacks-slowhttptest', 10: 'dos attacks-slowloris', 11: 'dos attacks-synflood', 12: 'ftp-bruteforce', 13: 'infilteration', 14: 'sql injection', 15: 'ssh-bruteforce'}


In [24]:
class_name = [mapper[index.item()+1] for index in class_idx]
print(class_name)

['ddos attack-hoic', 'dos attacks-hulk', 'benign', 'benign', 'benign', 'dos attacks-goldeneye', 'ssh-bruteforce', 'benign', 'benign', 'ssh-bruteforce', 'benign', 'benign', 'dos attacks-slowhttptest', 'benign', 'benign', 'benign', 'ddos attack-hoic', 'ddos attack-loic-udp', 'benign', 'ssh-bruteforce', 'benign', 'benign', 'dos attacks-slowloris', 'benign', 'dos attacks-slowhttptest', 'dos attacks-goldeneye', 'dos attacks-goldeneye', 'benign', 'benign', 'benign', 'benign', 'dos attacks-slowhttptest', 'benign', 'dos attacks-goldeneye', 'ddos attack-hoic', 'benign', 'dos attacks-slowloris', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'benign', 'dos attacks-slowloris', 'ddos attack-hoic', 'benign', 'benign', 'benign', 'benign', 'ddos attack-loic-udp', 'dos attacks-slowhttptest', 'benign', 'dos attacks-slowloris', 'dos attacks-slowloris', 'brute force -web', 'benign', 'ddos attack-hoic', 'benign', 'benign', 'dos attacks-hulk', 

In [26]:
import os


save_path = os.path.join('./model/model.pth')

torch.save(
                {
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                }
                , save_path)